In [ ]:
----------------------------------Human Activity Recorder------without Dimensionality redcution---------------------------------------------------

In [19]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
import time
from sklearn.metrics import classification_report
df = pd.read_csv("HAR.csv", header=None)
#print(df)

#statistic report
#print(df.describe())

#training and testing
X_test = df.drop(df.columns[[561]],axis=1)
y_test= df[561]
#print(X_test)
#print(y_test)

df1=pd.read_csv("HAR_train.csv",header=None)
X_train = df1.drop(df1.columns[[561]],axis=1)
y_train= df1[561]
#print(X_train)
#print(y_train)

#using Logistic 
start=time.time()
model_logistic = LogisticRegression(random_state=10)
model_logistic.fit(X_train,y_train)
end = time.time()
print("Execution time-logistic regression: ",end - start)
y_pred = model_logistic.predict(X_test)
print(classification_report(y_test,y_pred))

#using algorithms-bagging classifiers
start=time.time()
model = BaggingClassifier(n_estimators=100, random_state=0)
model.fit(X_train,y_train)
end = time.time()
print("Execution time-bagging classifier: ",end - start)
y_pred = model.predict(X_test)
print(classification_report(y_test,y_pred))

#uisng Random forest

start=time.time()
model1 = RandomForestClassifier(n_estimators=10, criterion='gini')
model1.fit(X_train,y_train)
end = time.time()
print("Execution time-Random forest: ",end - start)
y_pred = model1.predict(X_test)
print(classification_report(y_test,y_pred))

#using Decision tree
start=time.time()
model2 = DecisionTreeClassifier(random_state=0, max_depth=5)
model2.fit(X_train,y_train)
end = time.time()
print("Execution time-decision tree: ",end - start)
y_pred = model2.predict(X_test)
print(classification_report(y_test,y_pred))


C:\Users\Karthikeyan\Anaconda3\anoconda\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


Execution time-logistic regression:  3.3477933406829834
              precision    recall  f1-score   support

           1       0.91      0.88      0.89       243
           2       0.80      0.82      0.81       229
           3       0.84      0.79      0.82       239
           4       0.79      0.80      0.79       289
           5       0.76      0.81      0.78       254
           6       0.96      0.94      0.95       238

    accuracy                           0.84      1492
   macro avg       0.84      0.84      0.84      1492
weighted avg       0.84      0.84      0.84      1492

Execution time-bagging classifier:  353.6915285587311
              precision    recall  f1-score   support

           1       0.84      0.88      0.86       243
           2       0.88      0.78      0.83       229
           3       0.84      0.85      0.85       239
           4       0.96      0.77      0.85       289
           5       0.77      0.98      0.86       254
           6       0.9

In [ ]:
--------------------with Dimensionality reduction----------------------PCA------------------

In [38]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
import time
from sklearn.metrics import classification_report
from sklearn.decomposition import PCA
from sklearn.metrics import confusion_matrix


df1=pd.read_csv("HAR_train.csv",header=None)
X_train = df1.drop(df1.columns[[561]],axis=1)
y_train= df1[561]
#print(X_train)
#print(y_train)


df = pd.read_csv("HAR.csv", header=None)
X_test = df.drop(df.columns[[561]],axis=1)
y_test= df[561]
#print(X_test)
#print(y_test)


start=time.time()
#Uisng Dimensionality Reduction--PCA 
pca = PCA(n_components=5)
pca.fit(X_train)
trans=pca.transform(X_train)
#print("Transformed X_train")
#print(trans)


pca1 = PCA(n_components=5)
pca1.fit(X_test)
trans1=pca1.transform(X_test)
#print("Transformed X_test")
#print(trans1)
end = time.time()
print("Execution time for transforming : ",end - start)


#using Logistic 
start=time.time()
model_logistic = LogisticRegression(random_state=10)
model_logistic.fit(trans,y_train)
end = time.time()
print("Execution time-logistic regression: ",end - start)
y_pred = model_logistic.predict(trans1)
print(classification_report(y_test,y_pred))
print (confusion_matrix(y_test,y_pred))

#using algorithms-bagging classifiers
start=time.time()
model = BaggingClassifier(n_estimators=100, random_state=0)
model.fit(trans,y_train)
end = time.time()
print("Execution time-bagging classifier: ",end - start)
y_pred = model.predict(trans1)
print(classification_report(y_test,y_pred))
print (confusion_matrix(y_test,y_pred))

#uisng Random forest

start=time.time()
model1 = RandomForestClassifier(n_estimators=10, criterion='gini')
model1.fit(trans,y_train)
end = time.time()
print("Execution time-Random forest: ",end - start)
y_pred = model1.predict(trans1)
print(classification_report(y_test,y_pred))
print (confusion_matrix(y_test,y_pred))

#using Decision tree
start=time.time()
model2 = DecisionTreeClassifier(random_state=0, max_depth=5)
model2.fit(trans,y_train)
end = time.time()
print("Execution time-decision tree: ",end - start)
y_pred = model2.predict(trans1)
print(classification_report(y_test,y_pred))
print (confusion_matrix(y_test,y_pred))

Execution time for transforming :  0.39577388763427734


C:\Users\Karthikeyan\Anaconda3\anoconda\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


Execution time-logistic regression:  0.5681862831115723
              precision    recall  f1-score   support

           1       0.42      0.67      0.52       243
           2       0.52      0.41      0.46       229
           3       0.45      0.19      0.27       239
           4       0.39      0.87      0.54       289
           5       0.12      0.04      0.06       254
           6       0.10      0.04      0.05       238

    accuracy                           0.38      1492
   macro avg       0.33      0.37      0.32      1492
weighted avg       0.33      0.38      0.32      1492

[[162  48  33   0   0   0]
 [ 62  94   9   9  51   4]
 [159  23  45   3   6   3]
 [  0   3   5 250   6  25]
 [  0  12   6 174  11  51]
 [  0   1   2 208  18   9]]
Execution time-bagging classifier:  4.002925634384155
              precision    recall  f1-score   support

           1       0.54      0.66      0.60       243
           2       0.64      0.65      0.65       229
           3       0.

In [ ]:
--------------------------dimensionality reduction-------------------------------LinearDiscriminantAnalysis-----------

In [46]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
import time
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

df1=pd.read_csv("HAR_train.csv",header=None)
X_train = df1.drop(df1.columns[[561]],axis=1)
y_train= df1[561]
#print(X_train)
#print(y_train)


df = pd.read_csv("HAR.csv", header=None)
X_test = df.drop(df.columns[[561]],axis=1)
y_test= df[561]
#print(X_test)
#print(y_test)
start=time.time()
#Uisng Dimensionality Reduction--Linear method 
lda = LinearDiscriminantAnalysis()
X_lda = lda.fit_transform(X_test,y_test)
#print(X_lda.shape)
#print(X_lda)

lda1 = LinearDiscriminantAnalysis()
X1_lda = lda1.fit_transform(X_train,y_train)
#print(X1_lda.shape)
#print(X1_lda)
end = time.time()
print("transformation-Linear : ",end - start)

#using Logistic 
start=time.time()
model_logistic = LogisticRegression(random_state=10)
model_logistic.fit(X1_lda,y_train)
end = time.time()
print("Execution time-logistic regression: ",end - start)
y_pred = model_logistic.predict(X_lda)
print(classification_report(y_test,y_pred))
print (confusion_matrix(X_lda,y_pred))


#using algorithms-bagging classifiers
start=time.time()
model = BaggingClassifier(n_estimators=100, random_state=0)
model.fit(X1_lda,y_train)
end = time.time()
print("Execution time-bagging classifier: ",end - start)
y_pred = model.predict(X_lda)
print(classification_report(y_test,y_pred))
print (confusion_matrix(y_test,y_pred))

#uisng Random forest

start=time.time()
model1 = RandomForestClassifier(n_estimators=10, criterion='gini')
model1.fit(X1_lda,y_train)
end = time.time()
print("Execution time-Random forest: ",end - start)
y_pred = model1.predict(X_lda)
print(classification_report(y_test,y_pred))
print (confusion_matrix(y_test,y_pred))

#using Decision tree
start=time.time()
model2 = DecisionTreeClassifier(random_state=0, max_depth=5)
model2.fit(X1_lda,y_train)
end = time.time()
print("Execution time-decision tree: ",end - start)
y_pred = model2.predict(X_lda)
print(classification_report(y_test,y_pred))
print (confusion_matrix(y_test,y_pred))


transformation-Linear :  3.6166629791259766


C:\Users\Karthikeyan\Anaconda3\anoconda\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


Execution time-logistic regression:  0.5497117042541504
              precision    recall  f1-score   support

           1       0.99      1.00      1.00       243
           2       0.00      0.00      0.00       229
           3       0.09      0.10      0.09       239
           4       0.38      0.08      0.13       289
           5       0.03      0.03      0.03       254
           6       0.00      0.00      0.00       238

    accuracy                           0.20      1492
   macro avg       0.25      0.20      0.21      1492
weighted avg       0.26      0.20      0.21      1492

Execution time-bagging classifier:  3.1689789295196533
              precision    recall  f1-score   support

           1       0.99      1.00      0.99       243
           2       0.07      0.07      0.07       229
           3       0.06      0.05      0.06       239
           4       0.44      0.25      0.32       289
           5       0.01      0.00      0.00       254
           6       0.

In [ ]:
-----------------------dimenensionality reduction-----------------------Random Projection Sparse---------------------

In [44]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
import time
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.random_projection import SparseRandomProjection


df = pd.read_csv("HAR.csv", header=None)
#print(df)

#statistic report
#print(df.describe())

#training and testing
X_test = df.drop(df.columns[[561]],axis=1)
y_test= df[561]
#print(X_test)
#print(y_test)
df1=pd.read_csv("HAR_train.csv",header=None)
X_train = df.drop(df.columns[[561]],axis=1)
y_train= df[561]
#print(X_train)
#print(y_train)

#Uisng Dimensionality Reduction--Randome method 


start=time.time()
transformer = SparseRandomProjection(n_components=4)
X_new = transformer.fit_transform(X_test)
X_new.shape
#print(X_new)

transformer = SparseRandomProjection(n_components=4)
X1_new = transformer.fit_transform(X_train)
X1_new.shape
#print(X1_new)
end = time.time()
print("transformation-random : ",end - start)

#using Logistic 
start=time.time()
model_logistic = LogisticRegression(random_state=10)
model_logistic.fit(X1_new,y_train)
end = time.time()
print("Execution time-logistic regression: ",end - start)
y_pred = model_logistic.predict(X_new)
print(classification_report(y_test,y_pred))
print (confusion_matrix(y_test,y_pred))

#using algorithms-bagging classifiers
start=time.time()
model = BaggingClassifier(n_estimators=100, random_state=0)
model.fit(X1_new,y_train)
end = time.time()
print("Execution time-bagging classifier: ",end - start)
y_pred = model.predict(X_new)
print(classification_report(y_test,y_pred))
print (confusion_matrix(y_test,y_pred))

#uisng Random forest

start=time.time()
model1 = RandomForestClassifier(n_estimators=10, criterion='gini')
model1.fit(X1_new,y_train)
end = time.time()
print("Execution time-Random forest: ",end - start)
y_pred = model1.predict(X_new)
print(classification_report(y_test,y_pred))
print (confusion_matrix(y_test,y_pred))

#using Decision tree
start=time.time()
model2 = DecisionTreeClassifier(random_state=0, max_depth=5)
model2.fit(X1_new,y_train)
end = time.time()
print("Execution time-decision tree: ",end - start)
y_pred = model2.predict(X_new)
print(classification_report(y_test,y_pred))
print (confusion_matrix(y_test,y_pred))

transformation-random :  0.022986650466918945


C:\Users\Karthikeyan\Anaconda3\anoconda\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
C:\Users\Karthikeyan\Anaconda3\anoconda\lib\site-packages\sklearn\metrics\_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Execution time-logistic regression:  0.25885438919067383
              precision    recall  f1-score   support

           1       0.14      0.71      0.24       243
           2       0.09      0.01      0.02       229
           3       0.43      0.27      0.33       239
           4       0.00      0.00      0.00       289
           5       0.00      0.00      0.00       254
           6       0.29      0.12      0.17       238

    accuracy                           0.18      1492
   macro avg       0.16      0.19      0.13      1492
weighted avg       0.15      0.18      0.12      1492

Execution time-bagging classifier:  1.4007163047790527
              precision    recall  f1-score   support

           1       0.19      0.67      0.30       243
           2       0.19      0.15      0.17       229
           3       0.14      0.21      0.16       239
           4       0.35      0.02      0.04       289
           5       0.35      0.10      0.15       254
           6       0

In [ ]:
-----------------Dimensionality reduction--------------------Feature Agglomeration-------------------------------------------

In [53]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
import time
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn import datasets, cluster


df = pd.read_csv("HAR.csv", header=None)
#print(df)

#statistic report
#print(df.describe())

#training and testing
X_test = df.drop(df.columns[[561]],axis=1)
y_test= df[561]
#print(X_test)
#print(y_test)
df1=pd.read_csv("HAR_train.csv",header=None)
X_train = df.drop(df.columns[[561]],axis=1)
y_train= df[561]
#print(X_train)
#print(y_train)

#Uisng Dimensionality Reduction--Randome method 


start=time.time()


agglo = cluster.FeatureAgglomeration(n_clusters=4)
agglo.fit(X_test)
X_reduced = agglo.transform(X_test)
X_reduced.shape
#print("The X_test values")
#print(X_test)
#print("reduced X_test\n\n")
#print(X_reduced)


agglo = cluster.FeatureAgglomeration(n_clusters=4)
agglo.fit(X_train)
X1_reduced = agglo.transform(X_train)
X1_reduced.shape
#print("The X_train values")
#print(X_train)
#print("reduced X_train\n\n")
#print(X_reduced)

end = time.time()
print("transformation-feature : ",end - start)

#using Logistic 
start=time.time()
model_logistic = LogisticRegression(random_state=10)
model_logistic.fit(X1_reduced,y_train)
end = time.time()
print("Execution time-logistic regression: ",end - start)
y_pred = model_logistic.predict(X_reduced)
print(classification_report(y_test,y_pred))
print (confusion_matrix(y_test,y_pred))


#using algorithms-bagging classifiers
start=time.time()
model = BaggingClassifier(n_estimators=100, random_state=0)
model.fit(X1_reduced,y_train)
end = time.time()
print("Execution time-bagging classifier: ",end - start)
y_pred = model.predict(X_reduced)
print(classification_report(y_test,y_pred))
print (confusion_matrix(y_test,y_pred))

#uisng Random forest

start=time.time()
model1 = RandomForestClassifier(n_estimators=10, criterion='gini')
model1.fit(X1_reduced,y_train)
end = time.time()
print("Execution time-Random forest: ",end - start)
y_pred = model1.predict(X_reduced)
print(classification_report(y_test,y_pred))
print (confusion_matrix(y_test,y_pred))

#using Decision tree
start=time.time()
model2 = DecisionTreeClassifier(random_state=0, max_depth=5)
model2.fit(X1_reduced,y_train)
end = time.time()
print("Execution time-decision tree: ",end - start)
y_pred = model2.predict(X_reduced)
print(classification_report(y_test,y_pred))
print (confusion_matrix(y_test,y_pred))

transformation-feature :  0.8309354782104492
Execution time-logistic regression:  0.12891101837158203
              precision    recall  f1-score   support

           1       0.56      0.64      0.60       243
           2       0.43      0.54      0.47       229
           3       0.58      0.39      0.47       239
           4       0.40      0.69      0.51       289
           5       0.44      0.43      0.43       254
           6       0.07      0.00      0.01       238

    accuracy                           0.46      1492
   macro avg       0.41      0.45      0.41      1492
weighted avg       0.41      0.46      0.42      1492

[[156  59  28   0   0   0]
 [ 65 123  32   1   8   0]
 [ 59  84  94   0   2   0]
 [  0   4   1 200  76   8]
 [  0  11   2 127 108   6]
 [  0   8   6 170  53   1]]
Execution time-bagging classifier:  0.8430752754211426
              precision    recall  f1-score   support

           1       1.00      1.00      1.00       243
           2       1.00     

In [17]:
import numpy as np
import pandas as pd
df = pd.read_csv("HAR.csv", header=None)
print("counts :\n",df.count())
print("missing values :\n",df.info())
print("Sum of Row:\n",df.sum(axis = 0, skipna = True))
print("Sum of Column:\n",df.sum(axis = 1, skipna = True))


counts :
 0      1492
1      1492
2      1492
3      1492
4      1492
       ... 
557    1492
558    1492
559    1492
560    1492
561    1492
Length: 562, dtype: int64
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1492 entries, 0 to 1491
Columns: 562 entries, 0 to 561
dtypes: float64(561), int64(1)
memory usage: 6.4 MB
missing values :
 None
Sum of Row:
 0       480.724276
1       -19.822877
2      -147.177858
3      -993.050543
4      -854.619112
          ...     
557      -1.073291
558    -707.048012
559      59.108287
560     -85.321889
561    5272.000000
Length: 562, dtype: float64
Sum of Column:
 0      -198.222621
1      -277.241609
2      -289.974706
3      -330.781823
4      -333.507526
           ...    
1487   -354.816575
1488   -353.340635
1489   -354.119443
1490   -355.720368
1491   -354.935030
Length: 1492, dtype: float64
